services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: myjourney_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db:5432/myjourney_db
      JWT_SECRET: supersecretjwtkey_dev
      BACKEND_INTERNAL_URL: http://backend:3001
      BACKEND_EXTERNAL_URL: http://backend:3001
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - db # Backend now only waits for DB to be started

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      VITE_API_BASE_URL: /api # 'serve' will proxy this to the backend
    ports:
      - "8080:8080" # Expose frontend service directly
    restart: always
    depends_on:
      - backend # Frontend now only waits for backend to be started

volumes:
  db_data: